function drink_info_fr() //gml_Script_drink_info_fr
{
    if (current_scene == 0)
    {
        list_drink_material = ["Lait", "Café", "Sirop"]
        drink_menu = ["Coupe Harmonie", "Espresso Intenso", "Lait", "Espresso Velours", "Café Douceur", "Brise Miel Légère", "Confort Nuageux", "Soie de Sirop", "Cascade de Crème", "Essence Sucrée"]
        drink_descrip = ["Un mélange parfaitement équilibré de café, lait et une touche de douceur, harmonisant toutes les saveurs.", "Un espresso pur et fort pour ceux qui apprécient le goût inaltéré du café.", "Juste du lait chaud", "Doux et crémeux, cette boisson combine la profondeur riche du café avec la texture veloutée du lait.", "Un café audacieux adouci par une touche de douceur, idéal pour une expérience légèrement stimulante.", "Légèrement caféiné et agréablement sucré, parfait pour ceux qui aiment une touche douce de café.", "Une boisson crémeuse au lait avec une finition douce, idéale pour les moments de détente.", "Lait soyeux enrichi de double sirop pour un goût luxueusement sucré.", "Une cascade de lait crémeux s'écoule sur une base de café riche, créant une texture lisse et luxueuse.", "Une concoction intense de sirop seulement pour ceux qui savourent l'essence pure et sucrée."]
    }
    else if (current_scene == 1)
    {
        list_drink_material = ["Spiritueux", "Jus", "Liqueur"]
        drink_menu = ["Disjoncteur", "Bad Touch", "Brume Cybernétique", "Explosion Photonique", "Piano Man", "Moonblast", "Nuit Chrome", "Buzz Électro", "Flux de Données", "Synchronisation Neuronale"]
        drink_descrip = ["Une boisson qui perturbe les sens, offrant un goût de rébellion contre les seigneurs numériques.", "Alma veut un… pffft… un Bad Touch.", "Un cocktail mystérieux et énigmatique, son essence argentée évoquant l'incertitude brumeuse de l'avenir.", "Un cocktail vif et rafraîchissant, avec une qualité luminescente qui semble chargée d'énergie.", "Une boisson bizarre. Hm… Les boissons Promo conviennent facilement.", "Quelque chose de petit, sucré et glacé.", "Une boisson fraîche et élégante pour les noctambules urbains, reflétant l'éclat métallique de la ville sous la lune.", "Une boisson avec un coup de fouet puissant, énergisant le buveur pour une nuit de piratage et d'exploration.", "Un cocktail lisse et coulant, symbolisant le flux incessant d'informations dans le domaine cybernétique.", "Un shot pur et non dilué de Liqueur Néon, pour ceux qui cherchent à se connecter directement au réseau néon."]
    }
    else if (current_scene == 2)
    {
        list_drink_material = ["Thé Vert", "Jasmin", "Goji"]
        drink_menu = ["Brise de Jade", "Aurore de Jasmin", "Élixir d'Immortalité", "Fleur de Trinité", "Dame Dragon", "Nectar Royal", "Vestige de Beauté", "Secret Impérial", "Fleurs au Clair de Lune", "Orchidée de l'Érudit"]
        drink_descrip = ["Pur plaisir du thé vert, rafraîchissant et rajeunissant, favori parmi les anciens savants et poètes.", "Une base de thé vert avec une touche de parfum de jasmin, frais et élégant avec un doux parfum floral.", "Un mélange nourrissant de baies de goji et l'arôme frais du thé vert, offrant santé et vitalité.", "Une harmonie parfaite de trois ingrédients, symbolisant un équilibre et une unité des saveurs.", "Dominé par un parfum envoûtant de jasmin sur une base de thé vert, persistant comme le toucher d'une beauté ancienne jouant du guqin.", "Jasmin parfumé associé à de douces baies de goji, se renforçant mutuellement, semblable à une promenade dans un jardin céleste.", "Centré sur les bienfaits pour la santé des baies de goji complétées par la fraîcheur du thé vert, une boisson pour la longévité.", "Un mélange nutritif de goji avec le jasmin aromatique, autrefois une boisson royale de choix.", "Thé pur au jasmin, intensément floral et apaisant, célèbre pour ses qualités sereines et son arôme agréable.", "Infusé exclusivement à partir de baies de goji, symbolisant la noblesse et la longévité d'un érudit."]
    }
    else if (current_scene == 3)
    {
        list_drink_material = ["Whisky", "Rhum", "Vermouth"]
        drink_menu = ["Rob Roy", "Clou Rouillé", "Manhattan Parfait", "Vieux Cubain", "Dark 'n' Stormy", "Cable Car", "Mai Tai", "Negroni", "Vieux Carré", "Punch du Planteur"]
        drink_descrip = ["Un cocktail classique à base de whisky écossais, simple mais élégant.", "Un mélange de whisky et de rhum, combinant la douceur avec la force.", "Une variante du cocktail Manhattan, équilibrant le vermouth avec le whisky.", "Mélangeant les saveurs classiques cubaines avec le whisky et le vermouth.", "La puissance du rhum, profonde et captivante.", "Inspiré par les tramways de San Francisco, combinant rhum et whisky.", "Un classique saveur tropicale, merveilleusement mélangeant rhum et vermouth.", "Un cocktail italien classique dominé par le vermouth, amer-doux.", "Un cocktail classique de la Nouvelle-Orléans, complexe et profond.", "Un cocktail caribéen traditionnel, connu pour ses saveurs audacieuses et son goût robuste."]
    }
    else if (current_scene == 4)
    {
        list_drink_material = ["Herbes", "Baies", "Vin"]
        drink_menu = ["Brassage de l'herboriste", "Nectar de Baies de Bois", "Réserve du Moine", "Brouillon de Baies du Vigneron", "Mélange du Baron", "Jubilé des Baies", "Velours Vintage", "Mélange du Jardinier", "Élixir de l'Apothicaire", "Récolte Abondante"]
        drink_descrip = ["Concocté à partir d'un trio de fines herbes, ce tonique est révéré pour ses qualités médicinales et revitalisantes.", "Un mélange luxuriant et rafraîchissant de baies mûres avec une touche d'essence d'herbes, évoquant la fraîcheur des bois.", "Une recette sacrée qui marie la sainteté des herbes à la richesse du vin vieilli au monastère.", "Une concoction vibrante où la jutosité des baies rencontre la sophistication du vin fin.", "Un mélange noble avec l'audace du vin et une touche de baies, digne de l'aristocratie.", "Une célébration des baies sous leur forme la plus pure, cette boisson est un festival de douceur naturelle.", "Un mélange exquis de millésimes sélectionnés, conçu pour offrir un goût riche et luxueux.", "Un mélange terreux et délicieux qui capture l'essence d'un jardin bien entretenu et d'un bon vin.", "Une concoction puissante, prisée pour ses propriétés digestives et apaisantes, inspirée des recettes traditionnelles d'apothicaires.", "Embrassant l'abondance de la récolte, ce mélange met en valeur toute la saveur des baies mûres avec une finition vineuse."]
    }
    else if (current_scene == 5)
    {
        list_drink_material = ["Eau électrolytique", "Concentré de protéines", "Gelée de vitamines"]
        drink_menu = ["Éclat Électrolytique", "Pulsion de Protéines", "Oscillation Microgravité", "Chromatiques de Vitamines", "Cristaux d'Énergie", "Gelée Multispectrale", "Bouclier contre les Radiations", "Gelée Sensorielle", "Fluide Biofeedback", "Dessert Spatial"]
        drink_descrip = ["Cette boisson utilise une formule spéciale d'équilibre électrolytique qui brille sous la lumière, améliorant la sécurité lors des activités nocturnes.", "Utilise la nanotechnologie pour permettre une absorption rapide des protéines dans le corps, idéale pour un rechargement rapide de l'énergie après des tâches spatiales de haute intensité.", "Infusée avec des micro-nanobulles qui créent des effets d'oscillation intéressants dans un environnement de microgravité, offrant une expérience de consommation unique.", "Cette boisson contient de la gelée de vitamines qui change de couleur en fonction des niveaux de pH, permettant aux astronautes de surveiller visuellement leur apport en vitamines.", "Caractérisée par des formes cristallines de protéines qui se dissolvent lentement, libérant continuellement de l'énergie et des nutriments, adaptées pour des tâches de longue durée.", "Chaque couleur de la gelée représente un spectre nutritionnel différent, permettant aux astronautes de choisir en fonction de leurs besoins nutritionnels.", "Incorpore des composants spéciaux anti-radiation pour aider à réduire les dommages des radiations dans l'espace, tout en fournissant un renforcement de la force.", "Cette boisson ajuste automatiquement sa douceur et sa texture selon l'état corporel de l'astronaute, en rechargeant de manière optimale l'énergie et les nutriments.", "Contient des capteurs de biofeedback qui peuvent surveiller et ajuster le contenu nutritionnel en temps réel pour répondre aux besoins spécifiques des astronautes.", "Conçue pour ressembler et goûter comme un dessert de la Terre, offrant confort et familiarité tout en étant riche en nutriments."]
    }
}

