function drink_info_de() //gml_Script_drink_info_de
{
    if (current_scene == 0)
    {
        list_drink_material = ["Milk", "Coffee", "Sirop"]
        drink_menu = ["Harmony Cup", "Espresso Intenso", "Milk", "Velvet Espresso", "Dulce Brew", "Honeyed Light", "Cloudy Comfort", "Syruped Silk", "Cream Cascade", "Sweet Essence"]
        drink_descrip = ["A perfectly balanced blend of coffee, milk, and a touch of sweetness, harmonizing all flavors.", "A pure, strong shot of espresso for those who appreciate the uncompromised taste of coffee.", "Just hot milk", "Smooth and creamy, this drink combines the rich depth of coffee with the velvety texture of milk.", "A bold coffee softened with a hint of sweetness, ideal for a gently uplifting experience.", "Lightly caffeinated and sweetly flavored, perfect for those who enjoy a softer coffee touch.", "A comforting, creamy milk drink with a sweet finish, ideal for relaxing moments.", "Silky smooth milk enriched with double syrup for a luxuriously sweet taste.", "A cascade of creamy milk flows over a base of rich coffee, creating a lush, smooth texture.", "An intense, syrup-only concoction for those who savor the pure, sweet essence."]
    }
    else if (current_scene == 1)
    {
        list_drink_material = ["Spirit", "Juice", "Liquor"]
        drink_menu = ["Circuit Breaker", "Bad Touch", "Cyber Mist", "Photon Blast", "Piano Man", "Moonblast", "Chrome Night", "Electro Buzz", "Data Stream", "Neural Sync"]
        drink_descrip = ["A drink that disrupts the senses, offering a taste of the rebellion against the digital overlords.", "Alma will einen… pffft… einen Bad Touch.", "A mysterious and enigmatic cocktail, its silver essence evoking the foggy uncertainty of the future.", "A sharp and refreshing cocktail, with a luminescent quality that seems to charge with energy.", "Ein seltsames Getränk. Hm… Promo-Getränke passen leicht dazu.", "Etwas Kleines, Süßes und Kaltes.", " A cool and sleek drink for the urban night crawler, reflecting the city's metallic sheen under the moonlight.", "A drink with a potent kick, energizing the drinker for a night of hacking and exploration.", "A smooth and flowing cocktail, symbolizing the endless flow of information in the cyber realm.", "A pure, undiluted shot of Neon Liquor, for those looking to connect directly to the neon grid."]
    }
    else if (current_scene == 2)
    {
        list_drink_material = ["Green Tea", "Jasmine", "Goji"]
        drink_menu = ["Jade Breeze", "Jasmine Dawn", "Elixir of Immortality", "Trinity Blossom", "Dragon Maiden", "Royal Nectar", "Beauty Remnant", "Imperial Secret", "Moonlit Blossoms", "Scholar’s Orchid"]
        drink_descrip = ["Pure green tea enjoyment, refreshing and rejuvenating, a favorite among ancient scholars and poets.", "A base of green tea with a touch of jasmine fragrance, fresh and elegant with a gentle floral scent.", "A nourishing combination of goji berries and the fresh aroma of green tea, offering both health and vitality.", "A perfect harmony of three ingredients, symbolizing a balance and unity of flavors.", "Dominantly fragrant jasmine with a base of green tea, lingering like the touch of an ancient beauty playing the guqin.", "Fragrant jasmine paired with sweet goji berries, enhancing each other, akin to wandering through a heavenly garden.", "Focused on the health benefits of goji berries complemented by the freshness of green tea, a drink for longevity.", "A nutritional blend of goji with the aromatic jasmine, once a royal beverage of choice.", "Pure jasmine tea, intensely floral and soothing, celebrated for its serene qualities and delightful aroma.", "Exclusively brewed from goji berries, symbolizing the nobility and longevity of a scholar."]
    }
    else if (current_scene == 3)
    {
        list_drink_material = ["Whiskey", "Rum", "Vermouth"]
        drink_menu = ["Rob Roy", "Rusty Nail", "Perfect Manhattan", "Old Cuban", "Dark 'n' Stormy", "Cable Car", "Mai Tai", "Negroni", "Vieux Carre", "Planter’s Punch"]
        drink_descrip = ["A classic cocktail based on Scotch whiskey, simple yet elegant.", "A blend of whiskey and rum, combining sweetness with strength.", "A variant of the Manhattan cocktail, balancing vermouth with whiskey.", "Mixing classic Cuban flavors with whiskey and vermouth.", "The power of rum, deep and captivating.", "Inspired by San Francisco's cable cars, combining rum and whiskey.", "A classic tropical flavor, wonderfully blending rum and vermouth.", "A classic Italian cocktail dominated by vermouth, bittersweet.", "A classic cocktail from New Orleans, complex and profound.", "A traditional Caribbean cocktail, known for its bold flavors and robust taste."]
    }
    else if (current_scene == 4)
    {
        list_drink_material = ["Kräuter", "Beeren", "Wein"]
        drink_menu = ["Brauer des Kräutermeisters", "Beerenholz Nektar", "Mönchsreserve", "Weinbauers Beerenentwurf", "Barons Mischung", "Beeren Jubiläum", "Vintage Samt", "Gärtner's Mischung", "Apotheker's Elixier", "Fruchtbare Ernte"]
        drink_descrip = ["Aus einem Trio feiner Kräuter gebraut, wird dieser Trank für seine medizinischen und belebenden Eigenschaften geschätzt.", "Eine üppige, erfrischende Mischung aus reifen Beeren und einem Hauch von Kräuteressenz, die die Frische des Waldes heraufbeschwört.", "Ein heiliges Rezept, das die Heiligkeit der Kräuter mit dem Reichtum des im Kloster gereiften Weins verbindet.", "Ein lebendiger Trank, in dem sich die Saftigkeit der Beeren mit der Raffinesse des edlen Weins vereint.", "Eine edle Mischung mit der Kühnheit des Weins und einem Hauch von Beere, passend für die Aristokratie.", "Eine Feier der Beeren in ihrer reinsten Form, dieses Getränk ist ein Fest der natürlichen Süße.", "Eine exquisite Mischung ausgewählter Jahrgänge, die darauf ausgelegt ist, einen vielschichtigen und luxuriösen Geschmack zu bieten.", "Eine erdige, köstliche Mischung, die das Wesen eines gepflegten Gartens und eines feinen Weins einfängt.", "Ein starkes Gebräu, das für seine verdauungsfördernden und beruhigenden Eigenschaften geschätzt wird, inspiriert von traditionellen Apothekerezepten.", "Diese Mischung, die die Fülle der Ernte umarmt, zeigt den vollen Geschmack reifer Beeren mit einem weinigen Abgang."]
    }
    else if (current_scene == 5)
    {
        list_drink_material = ["Elektrolytwasser", "Proteinkonzentrat", "Vitamin-Gelatine"]
        drink_menu = ["Elektrolyt-Glanz", "Protein-Impuls", "Mikrogravitations-Oszillation", "Vitamin-Chromatik", "Energiekristalle", "Multispektrum-Gelatine", "Strahlenschutz", "Sensorisches Gel", "Biofeedback-Flüssigkeit", "Weltraum-Dessert"]
        drink_descrip = ["Dieses Getränk verwendet eine spezielle Elektrolyt-Balance-Formel, die unter Licht leuchtet und so die Sicherheit bei nächtlichen Aktivitäten erhöht.", "Nutzt Nanotechnologie, um eine schnelle Absorption von Protein im Körper zu ermöglichen, ideal für schnelle Energieauffüllung nach hochintensiven Weltraumaufgaben.", "Angereichert mit Mikro-Nanobläschen, die in einer Mikrogravitationsumgebung interessante Oszillationseffekte erzeugen und ein einzigartiges Trinkerlebnis bieten.", "Dieses Getränk enthält Vitamin-Gelatine, die ihre Farben je nach pH-Wert ändert, was es Astronauten ermöglicht, ihre Vitaminzufuhr visuell zu überwachen.", "Merkmale spezieller kristalliner Proteinformen, die sich langsam auflösen und kontinuierlich Energie und Nährstoffe freisetzen, geeignet für langanhaltende Aufgaben.", "Jede Farbe der Gelatine repräsentiert ein anderes Nährstoffspektrum, was es Astronauten ermöglicht, basierend auf ihren Ernährungsbedürfnissen zu wählen.", "Enthält spezielle Strahlenschutzkomponenten, die dazu beitragen, Strahlenschäden im Weltraum zu reduzieren und gleichzeitig die Kraft zu steigern.", "Dieses Getränk passt automatisch seine Süße und Textur an den körperlichen Zustand des Astronauten an und optimiert so die Energie- und Nährstoffversorgung.", "Enthält Biofeedback-Sensoren, die den Nährstoffgehalt in Echtzeit überwachen und anpassen können, um den spezifischen Bedürfnissen der Astronauten gerecht zu werden.", "Entworfen, um wie ein Erdendessert auszusehen und zu schmecken, bietet es Komfort und Vertrautheit und ist gleichzeitig reich an Nährstoffen."]
    }
}

