function drink_info_it() //gml_Script_drink_info_it
{
    if (current_scene == 0)
    {
        list_drink_material = ["Milk", "Coffee", "Sirop"]
        drink_menu = ["Harmony Cup", "Espresso Intenso", "Milk", "Velvet Espresso", "Dulce Brew", "Honeyed Light", "Cloudy Comfort", "Syruped Silk", "Cream Cascade", "Sweet Essence"]
        drink_descrip = ["A perfectly balanced blend of coffee, milk, and a touch of sweetness, harmonizing all flavors.", "A pure, strong shot of espresso for those who appreciate the uncompromised taste of coffee.", "Just hot milk", "Smooth and creamy, this drink combines the rich depth of coffee with the velvety texture of milk.", "A bold coffee softened with a hint of sweetness, ideal for a gently uplifting experience.", "Lightly caffeinated and sweetly flavored, perfect for those who enjoy a softer coffee touch.", "A comforting, creamy milk drink with a sweet finish, ideal for relaxing moments.", "Silky smooth milk enriched with double syrup for a luxuriously sweet taste.", "A cascade of creamy milk flows over a base of rich coffee, creating a lush, smooth texture.", "An intense, syrup-only concoction for those who savor the pure, sweet essence."]
    }
    else if (current_scene == 1)
    {
        list_drink_material = ["Spirit", "Juice", "Liquor"]
        drink_menu = ["Circuit Breaker", "Bad Touch", "Cyber Mist", "Photon Blast", "Piano Man", "Moonblast", "Chrome Night", "Electro Buzz", "Data Stream", "Neural Sync"]
        drink_descrip = ["A drink that disrupts the senses, offering a taste of the rebellion against the digital overlords.", "Alma vuole un… pffft… un Bad Touch.", "A mysterious and enigmatic cocktail, its silver essence evoking the foggy uncertainty of the future.", "A sharp and refreshing cocktail, with a luminescent quality that seems to charge with energy.", "Una bevanda strana. Hm… Le bevande promozionali si adattano facilmente.", "Qualcosa di piccolo, dolce e ghiacciato.", " A cool and sleek drink for the urban night crawler, reflecting the city's metallic sheen under the moonlight.", "A drink with a potent kick, energizing the drinker for a night of hacking and exploration.", "A smooth and flowing cocktail, symbolizing the endless flow of information in the cyber realm.", "A pure, undiluted shot of Neon Liquor, for those looking to connect directly to the neon grid."]
    }
    else if (current_scene == 2)
    {
        list_drink_material = ["Green Tea", "Jasmine", "Goji"]
        drink_menu = ["Jade Breeze", "Jasmine Dawn", "Elixir of Immortality", "Trinity Blossom", "Dragon Maiden", "Royal Nectar", "Beauty Remnant", "Imperial Secret", "Moonlit Blossoms", "Scholar’s Orchid"]
        drink_descrip = ["Pure green tea enjoyment, refreshing and rejuvenating, a favorite among ancient scholars and poets.", "A base of green tea with a touch of jasmine fragrance, fresh and elegant with a gentle floral scent.", "A nourishing combination of goji berries and the fresh aroma of green tea, offering both health and vitality.", "A perfect harmony of three ingredients, symbolizing a balance and unity of flavors.", "Dominantly fragrant jasmine with a base of green tea, lingering like the touch of an ancient beauty playing the guqin.", "Fragrant jasmine paired with sweet goji berries, enhancing each other, akin to wandering through a heavenly garden.", "Focused on the health benefits of goji berries complemented by the freshness of green tea, a drink for longevity.", "A nutritional blend of goji with the aromatic jasmine, once a royal beverage of choice.", "Pure jasmine tea, intensely floral and soothing, celebrated for its serene qualities and delightful aroma.", "Exclusively brewed from goji berries, symbolizing the nobility and longevity of a scholar."]
    }
    else if (current_scene == 3)
    {
        list_drink_material = ["Whiskey", "Rum", "Vermouth"]
        drink_menu = ["Rob Roy", "Rusty Nail", "Perfect Manhattan", "Old Cuban", "Dark 'n' Stormy", "Cable Car", "Mai Tai", "Negroni", "Vieux Carre", "Planter’s Punch"]
        drink_descrip = ["A classic cocktail based on Scotch whiskey, simple yet elegant.", "A blend of whiskey and rum, combining sweetness with strength.", "A variant of the Manhattan cocktail, balancing vermouth with whiskey.", "Mixing classic Cuban flavors with whiskey and vermouth.", "The power of rum, deep and captivating.", "Inspired by San Francisco's cable cars, combining rum and whiskey.", "A classic tropical flavor, wonderfully blending rum and vermouth.", "A classic Italian cocktail dominated by vermouth, bittersweet.", "A classic cocktail from New Orleans, complex and profound.", "A traditional Caribbean cocktail, known for its bold flavors and robust taste."]
    }
    else if (current_scene == 4)
    {
        list_drink_material = ["Erbe", "Bacche", "Vino"]
        drink_menu = ["Infuso dell'Erborista", "Nettare di Bacche di Bosco", "Riserva del Monaco", "Bozza di Bacche del Vinificatore", "Misto del Barone", "Giubileo di Bacche", "Velluto Vintage", "Misto del Giardiniere", "Elisir dell'Apotecario", "Raccolto Fruttuoso"]
        drink_descrip = ["Creato da un trio di erbe pregiate, questo tonico è venerato per le sue qualità medicinali e rivitalizzanti.", "Un mix rigoglioso e rinfrescante di bacche mature con un tocco di essenza erbacea, che evoca la freschezza del bosco.", "Una ricetta sacra che unisce la santità delle erbe con la ricchezza del vino invecchiato nel monastero.", "Un vivace mix in cui la succosità delle bacche incontra la raffinatezza del vino pregiato.", "Un nobile mix con l'audacia del vino e un tocco di bacca, adatto per l'aristocrazia.", "Una celebrazione delle bacche nella loro forma più pura, questa bevanda è un festival di dolcezza naturale.", "Un'esclusiva miscela di annate selezionate, creata per offrire un gusto ricco e lussuoso.", "Un mix terroso e delizioso che cattura l'essenza di un giardino ben curato e di un buon vino.", "Una potente miscela apprezzata per le sue proprietà digestive e calmanti, ispirata a ricette tradizionali di apotecari.", "Abbracciando l'abbondanza del raccolto, questa miscela mette in mostra tutto il sapore delle bacche mature con una finitura di vino."]
    }
    else if (current_scene == 5)
    {
        list_drink_material = ["Acqua Elettrolitica", "Concentrato di Proteine", "Gelatina di Vitamine"]
        drink_menu = ["Splendore Elettrolitico", "Impulso di Proteine", "Oscillazione Microgravitazionale", "Cromatiche di Vitamine", "Cristalli di Energia", "Gelatina Multispettro", "Scudo Antiradiazione", "Gelatina Sensoriale", "Fluido di Biofeedback", "Dessert Spaziale"]
        drink_descrip = ["Questa bevanda utilizza una formula speciale di equilibrio elettrolitico che brilla sotto la luce, migliorando la sicurezza durante le attività notturne.", "Utilizza la nanotecnologia per permettere un rapido assorbimento delle proteine nel corpo, ideale per un rapido reintegro energetico dopo compiti spaziali ad alta intensità.", "Infusa con micro-nanobolle che creano effetti di oscillazione interessanti in un ambiente di microgravità, offrendo un'esperienza di consumo unica.", "Questa bevanda contiene gelatina di vitamine che cambia colore in base ai livelli di pH, permettendo agli astronauti di monitorare visivamente il loro apporto di vitamine.", "Caratteristiche di forme cristalline di proteine che si dissolvono lentamente, rilasciando energia e nutrienti continuamente, adatte per compiti di lunga durata.", "Ogni colore della gelatina rappresenta uno spettro nutrizionale diverso, consentendo agli astronauti di scegliere in base alle loro necessità nutrizionali.", "Incorpora componenti speciali anti-radiazione per aiutare a ridurre i danni da radiazioni nello spazio, fornendo anche un aumento di forza.", "Questa bevanda regola automaticamente la sua dolcezza e texture in base allo stato corporeo dell'astronauta, ricaricando energia e nutrienti in modo ottimale.", "Contiene sensori di biofeedback che possono monitorare e regolare il contenuto nutrizionale in tempo reale per soddisfare le esigenze specifiche degli astronauti.", "Progettata per assomigliare e assaporare come un dessert terrestre, fornendo comfort e familiarità pur essendo ricca di nutrienti."]
    }
}

