function all_music() //gml_Script_all_music
{
    album_list[0] = [mc_flying, mc_precious_morning, mc_solitude, mc_iwillcarryyou, mc_valley, mc_ottom, mc_flight, mc_i_knowitsok, mc_sentimental, mc_cupotea, mc_onechance, mc_liftoff, mc_astra, mc_holy, mc_istill]
    album_name_list[0] = ["Flying on your skin - Delnova", "Precious Mornings - Nobou ", "Solitude - Michael Drake", "I Will Carry You - Smplsmth", "Valley - Lolek", "Slush - Ottom", "Flight - Joley", "I know it's OK - Smplsmth", "Sentimentality - christopher galovan", "Cup o'tea - Lalinea", "One Chance - Eric Haley", "Lift Off - Smplsmth", "Astra - Magiksolo", "Holy - Delnova", "I still - Solar Body"]
    album_list[1] = [Juvenile___Miles_from_Perseus, Juvenile___White_Vacancy, Imaginary_Towers___Hills_We_Were_Willing_to_Die_On, Thirds, Evgeny_Bardyuzha___Sweet_Sorrow, Infinite, Captain_Qubz___Nice_Wave, HVRDVR___City_Lights, Para_Dot___Massive_Aglow, _2050___That_Night, Luke_Melville___Sugar_Cone]
    album_name_list[1] = ["Miles from Perseu - Juvenile", "White Vacancy - Juvenile", "Hills We Were Willing to Die On", "Thirds - Jamie Bathgate", "Sweet Sorrow - Evgeny Bardyuzha", "Infinite - Kuyani", "Captain Qubz Nice Wave", "HVRDVR city lights", "Para Dot Massive Aglow", "2050 That Night", "Luke Melville Sugar Cone"]
    album_list[2] = [inspiring_asia_116198, across_the_rivers_of_asia_143602, lost_memories_of_vietnam_144764, inspirational_vietnam_143600, somewhere_in_the_clouds_184456, audiobay_vietnamese_rivers_melody_mood_sad_slowly_150276, mid_autumn_festival_144765, moonlit_night_121800, vietnam_romance_144766, hoi_an_ancient_charm_147064, ha_long_bay_serenity_147067, asian_nightscape_144768, chinese_ancient_style_music_love_et11lx_155926, inspirational_asia_116956, chinese_classical_music_202971, kueissyo_203915]
    album_name_list[2] = ["Silk Road Serenade", "Lotus Blossom Lullaby", "Dragon Dance Dreams", "Jasmine Twilight", "Pagoda Shadows", "river melody mood", "Bamboo Whispers", "moonlit night", "Misty Mountain Meditation", "Ancient Capital Echoes", "Celestial River Flow", "Plum Blossom Melody", "Crane in the Clouds", "Serene Lotus Pond", "Red Lantern Rhapsody", "Forbidden City Nocturne"]
    album_list[3] = [Yonatan_Riklis___Blue_Rag, Kyle_Cox___Late_Night___Instrumental_Version, Novembers___Pour_Me_a_Cup_of_That, Kevin_Conlon___South_Side_Slide, Louis_Adrien___El_Diablo, Jason_Rosenblatt___Wisemans_Rag, Marek_Jakubowicz___Another_Rainy_Day, Ziv_Moran___Easy_Peasy, Reed_Pittman___Deck_the_Halls]
    album_name_list[3] = ["Yonatan Riklis Blue Rag", "Kyle Cox Late Night Instrumental Version", "Novembers Pour Me a Cup of That", "Kevin Conlon South Side Slide", "Louis Adrien El Diablo", "Jason Rosenblatt Wisemans_Rag", "Marek Jakubowicz Another Rainy Day", "Ziv Moran Easy Peasy", "Reed Pittman Deck the Halls"]
    album_list[4] = [TchaikovskySwanLake, BeethovenFurElise, interstellar, MozartTurkishMarch, BrahmsHungarianDanceNo5, BEETHOVENMoonlightSonata1stMovemen, ChopinNocturneop9No2, BeethovenSonataNo13inEFlatMajorOp27No1, BeethovenSonataNo1inFMinorOp2No1, SonataNo1inFMinorOp2No1IVPrestissimo, VivaldiSpringfromtheFourSeasons, ChopinWaltzB46InEFlatMajor, ChopinWaltzB56InEMinor, ClementiSonatainGMinor]
    album_name_list[4] = ["Tchaikovsky - Swan Lake", "Beethoven - Fur Elise", "Interstellar- Hans Zimmer", "Mozart  Turkish March ", "Brahms - Hungarian Dance No.5", "BEETHOVEN - Moonlight Sonata, 1st", "Chopin - Nocturne op.9 No.2", "Beethoven - Sonata No. 13 in E ", "Beethoven's Sonata No. 1 in F Minor", "Sonata No. 1 in F Minor, Op. 2 No. 1", "Vivaldi Spring from the Four Seasons", "Chopin - Waltz B46 In E-Flat Major", "Chopin - Waltz B56 In E Minor", "Clementi's Sonata in G Minor"]
    album_list[5] = [Hans_Zimmer___Interstellar_Main_Theme____Space_4k___no_copyright_Interstaller_inspired_Music, The_Music_of_Life__Copyright_free_background_music, Mystery__Free_mystery_music_for_YouTube_videos__no_copyright_, Calm_Cosmos__Free_Music__Royalty_Free_No_Copyright_, Free_Music_Retro_Sci_Fi_Music___Royalty_Free_No_Copyright_, Calm_Ambient_Sci_Fi_Fantasy_Music___Royalty_Free_No_Copyright_, Future_Renaissance__Epic_Sci_Fi_Trailer_Music___Royalty_Free_No_Copyright_, Entering_A_Black_Hole_Music_Copyright_Free]
    album_name_list[5] = ["Interstellar", "The music of life", "Mystery", "Calm Cosmos", "Retro journey", "Under the Galaxy", "Future Renaissance", "Entering a black hole"]
    album_list[6] = [ES_Callisto_8___Ben_Elson, ES_Hogarth___Lupus_Nocte, ES_The_Farmhouse___Silver_Maple, ES_Blush_Response___Hampus_Naeselius, ES_Titane___ELFL, ES_Concrete_Pilots___Modal_Youth, ES_Falling_Through___Particle_House, ES_Whisper___Particle_House, ES_Nothing_for_Me___Lupus_Nocte, ES_This_Is_Destruction___Particle_House, ES_Anyone_but_You___Particle_House, ES_A_Heart_Made_of_Pixels___Christoffer_Moe_Ditlevsen, ES_Amalthea___Van_Sandano, ES_Fractured_Paintings___Trevor_Kowalski, ES_Machine_Dreams___Oh_the_City, ES_Eupheme___Ben_Elson, ES_Peacewalker___ELFL, ES_Temple_of_Runha___ELFL]
    album_name_list[6] = ["Callisto 8", "Hogarth", "The Farmhouse", "Blush Response", "Titane", "Concrete Pilots", "Falling through", "Whisper", "Nothing for me", "This is Destruction", "Anyone but you", "A heart made of pixels", "Amalthea", "Fractured Paintings", "Machine dreams", "Eupheme", "Peacewalker", "Temple of runha"]
}

