particle_system = part_system_create_layer("WEATHER", 0)
particletype_rain = part_type_create()
part_type_sprite(particletype_rain, spr_particle_rain, 0, 0, 1)
part_type_size(particletype_rain, 1, 1.2, 0, 0)
part_type_gravity(particletype_rain, 0.1, 280)
part_type_life(particletype_rain, 150, 200)
part_type_orientation(particletype_rain, 0, 0, 0, 0, 0)
particletype_storm = part_type_create()
part_type_sprite(particletype_storm, spr_particle_rain, 0, 0, 1)
part_type_size(particletype_storm, 1, 1.2, 0, 0)
part_type_gravity(particletype_storm, 0.2, 280)
part_type_life(particletype_storm, 150, 200)
part_type_orientation(particletype_storm, 0, 0, 0, 0, 0)
xStart = camera_get_view_x(view_camera[0])
yStart = camera_get_view_y(view_camera[0]) - 400
camera_w = camera_get_view_width(view_camera[0])
emitterrain = part_emitter_create(particle_system)
part_emitter_region(particle_system, emitterrain, (xStart - 800), (xStart + 800 + camera_w), yStart, yStart, 0, 0)
part_emitter_stream(particle_system, emitterrain, particletype_rain, 10)
emitter_storm = part_emitter_create(particle_system)
part_emitter_region(particle_system, emitter_storm, (xStart - 800), (xStart + 800 + camera_w), yStart, yStart, 0, 0)
part_emitter_stream(particle_system, emitter_storm, particletype_storm, 20)
