function tutorial_text() //gml_Script_tutorial_text
{
    if (obj_controller.current_language == 0)
    {
        pages = ["Welcome to Chill Pulse, a game designed to help players focus and relax. Players can unlock different focus environments, choose their favorite scenes, and play their favorite music to start their journey of concentration. The gameplay will be introduced next.", "You can use a Pomodoro timer to set a period for focused work. Focusing earns you diamonds and focus points. Focus points can be used for upgrades, while diamonds can be spent on decorations, pets, and more. The higher your level, the more diamonds you earn.", "You can use a ToDoList to keep track of all your tasks. All completed items will be saved to the calendar, which you can view and delete as needed.", "You can access the Hub, where all your focus records, diaries, and game settings are stored.", "This is your communication device, see who might contact you for a chat!", "Here you can change character outfits, unlock pets, and keep fish.", "Here, you can travel through time and explore characteristic scenes from different periods.", "Here, you can send letters and exchange warm words with strangers from the other side of the world.", "You can switch between fullscreen mode and windowed mode at any time.", "You can choose your favorite white noise and weather.", "You can use sticky notes to record your various thoughts.", "You can use the online chatroom feature to chat with players from around the world! (This feature can be disabled in settings)"]
        text_tutorial = ["Tutorial", "Pomodoro Timer", "To Do List", "Hub", "Phone", "Accesoires", "Scene", "Mailbox", "Full screen mode", "Weather & Sounds", "Sticky notes", "Livechat"]
    }
    if (obj_controller.current_language == 1)
    {
        pages = ["欢迎来到 心流小筑，这是一个旨在帮助玩家专注和放松的\n游戏。玩家可以解锁不同的专注环境，选择他们喜欢的场景，\n并播放他们喜欢的音乐开始他们的专注之旅。接下来将介绍游戏玩法。", "您可以使用番茄工作法定时器设定专注工作的时间段。专注\n将为您赚取钻石和专注点。专注点可以用来升级，而钻石\n可以用来购买装饰品、宠物等。您的等级越高，赚取的钻石就越多。", "您可以使用待办事项列表来跟踪所有任务。所有完成的项目\n将被保存到日历中，您可以查看并删除这些项目。", "您可以访问中心区域，那里存放着您所有的专注记录、日记和游戏\n设置。", "这是您的通讯设备，看看谁可能联系您聊天！", "在这里，您可以更换角色装扮，解锁宠物，并饲养鱼。", "在这里，您可以穿越时光，探索来自不同时期的特色场景。", "在这里，您可以发送信件，并与世界另一端的陌生人交换温暖的\n话语。", "您可以随时切换全屏模式和非全屏模式。", "您可以选择您喜欢的白噪声和天气。", "您可以使用便利贴记录您的各种想法。", "您可以使用在线聊天室功能和全世界的玩家聊天！\n（此功能可以在设置里禁用）"]
        text_tutorial = ["教程", "番茄工作法定时器", "待办事项列表", "中心区域", "电话", "配饰", "场景", "邮箱", "全屏模式", "天气与声音", "便利贴", "实时聊天"]
    }
    if (obj_controller.current_language == 2)
    {
        pages = ["Chill Pulseへようこそ。これは、プレイヤーが集中しリ\nラックスするのを助けるゲームです。プレイヤーは異\nなる集中環境を解除し、好きなシーンを選んで、お気に入り\nの音楽を流して集中の旅を始めます。ゲームプレ\nイは次に紹介されます。", "ポモドーロタイマーを使って集中作業の時間を設定できま\nす。集中するとダイヤモンドと集中ポイントが獲得でき\nます。集中ポイントはアップグレードに使え、ダイヤモンド\nは装飾やペットなどに使えます。レベルが高いほど、\n獲得するダイヤモンドも多くなります。", "ToDoリストを使用してすべてのタスクを追跡できます。完了\nしたアイテムはカレンダーに保存され、必要に応じて表示および\n削除が可能です。", "すべての集中記録、日記、ゲーム設定が保存されているハブ\nにアクセスできます。", "これがあなたの通信デバイスです。誰がチャットに連絡してく\nるか確認してください！", "ここでキャラクターの服装を変更したり、ペットを解除したり、\n魚を飼育することができます。", "ここでは時間を旅して、異なる時代の特徴的なシーンを探索で\nきます。", "ここでは手紙を送り、世界の反対側の見知らぬ人と暖かい言葉を\n交換することができます。", "いつでも全画面モードとウィンドウモードを切り替えることができます。", "好きな白色ノイズと天候を選ぶことができます。", "様々な考えを記録するために付箋を使用することができます。", "オンラインチャットルーム機能を使って、世界中のプレイヤーとチャットできます！\n（この機能は設定で無効にできます）"]
        text_tutorial = ["チュートリアル", "ポモドーロタイマー", "ToDoリスト", "ハブ", "電話", "アクセサリー", "シーン", "メールボックス", "全画面モード", "天候とサウンド", "付箋", "ライブチャット"]
    }
    if (obj_controller.current_language == 3)
    {
        pages = ["歡迎來到 心流小筑，這是一個旨在幫助玩家專注和放鬆的\n遊戲。玩家可以解鎖不同的專注環境，選擇他們喜歡的場景，\n並播放他們喜歡的音樂開始他們的專注之旅。接下來將介紹遊戲玩法。", "您可以使用番茄工作法定時器設定專注工作的時間段。專注\n將為您賺取鑽石和專注點。專注點可以用來升級，而鑽石\n可以用來購買裝飾品、寵物等。您的等級越高，賺取的鑽石就越多。", "您可以使用待辦事項列表來跟蹤所有任務。所有完成的項目\n將被保存到日曆中，您可以查看並刪除這些項目。", "您可以訪問中心區域，那裡存放著您所有的專注記錄、日記和遊戲\n設定。", "這是您的通訊設備，看看誰可能聯繫您聊天！", "在這裡，您可以更換角色裝扮，解鎖寵物，並飼養魚。", "在這裡，您可以穿越時光，探索來自不同時期的特色場景。", "在這裡，您可以發送信件，並與世界另一端的陌生人交換溫暖的\n話語。", "您可以隨時切換全屏模式和非全屏模式。", "您可以選擇您喜歡的白噪聲和天氣。", "您可以使用便利貼記錄您的各種想法。", "您可以使用線上聊天室功能和全世界的玩家聊天！\n（此功能可以在設定裡禁用）"]
        text_tutorial = ["教程", "番茄工作法定時器", "待辦事項列表", "中心區域", "電話", "配飾", "場景", "郵箱", "全屏模式", "天氣與聲音", "便利貼", "即時聊天"]
    }
    if (obj_controller.current_language == 4)
    {
        pages = ["Bienvenue à Chill Pulse, un jeu conçu pour aider les joueurs à se concentrer et se détendre. Les joueurs peuvent déverrouiller différents environnements de concentration, choisir leurs scènes préférées, et jouer leur musique favorite pour commencer leur voyage de concentration. Le gameplay sera introduit ensuite.", "Vous pouvez utiliser un minuteur Pomodoro pour définir une période de travail concentré. Se concentrer vous permet de gagner des diamants et des points de concentration. Les points de concentration peuvent être utilisés pour des améliorations, tandis que les diamants peuvent être dépensés en décorations, animaux de compagnie, et plus encore. Plus votre niveau est élevé, plus vous gagnez de diamants.", "Vous pouvez utiliser une liste de tâches pour suivre toutes vos tâches. Tous les éléments complétés seront sauvegardés dans le calendrier, que vous pouvez consulter et supprimer selon le besoin.", "Vous pouvez accéder au Hub, où tous vos enregistrements de concentration, journaux intimes, et paramètres de jeu sont stockés.", "Ceci est votre dispositif de communication, voyez qui pourrait vous contacter pour discuter !", "Ici, vous pouvez changer les tenues des personnages, déverrouiller des animaux de compagnie, et garder des poissons.", "Ici, vous pouvez voyager à travers le temps et explorer des scènes caractéristiques de différentes époques.", "Ici, vous pouvez envoyer des lettres et échanger des mots chaleureux avec des étrangers de l'autre côté du monde.", "Vous pouvez passer à tout moment entre le mode plein écran et le mode fenêtré.", "Vous pouvez choisir votre bruit blanc préféré et la météo.", "Vous pouvez utiliser des post-it pour enregistrer vos diverses pensées.", "Vous pouvez utiliser la fonction de chat en ligne pour discuter avec des joueurs du monde entier ! \n(Cette fonction peut être désactivée dans les paramètres)"]
        text_tutorial = ["Tutoriel", "Minuteur Pomodoro", "Liste de Tâches", "Hub", "Téléphone", "Accessoires", "Scène", "Boîte aux lettres", "Mode plein écran", "Météo & Sons", "Post-it", "Chat en direct"]
    }
    if (obj_controller.current_language == 5)
    {
        pages = ["Добро пожаловать в Chill Pulse, игру, созданную чтобы помочь игрокам сосредоточиться и расслабиться. Игроки могут разблокировать различные среды для концентрации, выбирать любимые сцены и включать любимую музыку, чтобы начать свое путешествие к концентрации. Геймплей будет представлен далее.", "Вы можете использовать таймер Помодоро, чтобы установить период сосредоточенной работы. Концентрация принесет вам алмазы и очки концентрации. Очки концентрации можно использовать для улучшений, а алмазы тратить на украшения, питомцев и многое другое. Чем выше ваш уровень, тем больше алмазов вы заработаете.", "Вы можете использовать список задач для отслеживания всех ваших задач. Все завершенные элементы будут сохранены в календаре, который вы можете просматривать и удалять по мере необходимости.", "Вы можете получить доступ к Хабу, где хранятся все ваши записи о концентрации, дневники и настройки игры.", "Это ваше средство связи, посмотрите, кто может связаться с вами для чата!", "Здесь вы можете менять наряды персонажей, разблокировать питомцев и содержать рыб.", "Здесь вы можете путешествовать во времени и исследовать характерные сцены из разных периодов.", "Здесь вы можете отправлять письма и обмениваться теплыми словами с незнакомцами с другой стороны мира.", "Вы можете в любое время переключаться между полноэкранным режимом и оконным", "Вы можете выбрать свой любимый белый шум и погоду.", "Вы можете использовать стикеры для записи различных мыслей.", "Вы можете использовать функцию онлайн-чата, чтобы общаться с игроками со всего мира!\n (Эту функцию можно отключить в настройках)"]
        text_tutorial = ["Учебник", "Таймер Помодоро", "Список задач", "Хаб", "Телефон", "Аксессуары", "Сцена", "Почтовый ящик", "Полноэкранный режим", "Погода и звуки", "Стикеры", "Живой чат"]
    }
    if (obj_controller.current_language == 6)
    {
        pages = ["Chill Pulse에 오신 것을 환영합니다. 플레이어가 집중하고 휴식할 수 있도록 돕는 게임입니다. 플레이어는 다양한 집중 환경을 잠금 해제할 수 있으며, 좋아하는 장면을 선택하고 좋아하는 음악을 플레이하여 집중 여정을 시작할 수 있습니다. 게임 플레이는 다음에 소개될 것입니다.", "포모도로 타이머를 사용하여 집중 작업 기간을 설정할 수 있습니다. 집중을 하면 다이아몬드와 집중 포인트를 얻을 수 있습니다. 집중 포인트는 업그레이드에 사용할 수 있으며, 다이아몬드는 장식품, 애완동물 등에 사용할 수 있습니다. 레벨이 높을수록 더 많은 다이아몬드를 벌 수 있습니다.", "할 일 목록을 사용하여 모든 작업을 추적할 수 있습니다. 완료된 항목은 캘린더에 저장되며 필요에 따라 확인 및 삭제할 수 있습니다.", "모든 집중 기록, 일기, 게임 설정이 저장된 허브에 접속할 수 있습니다.", "이것은 당신의 통신 장치입니다, 누가 채팅을 위해 연락할지 확인해보세요!", "여기서 캐릭터 의상을 변경하거나 애완동물을 잠금 해제하고 물고기를 키울 수 있습니다.", "여기서 시간을 여행하며 다양한 시대의 특징적인 장면들을 탐험할 수 있습니다.", "여기서 편지를 보내고 세계의 다른 쪽에 있는 낯선 사람들과 따뜻한 말을 주고받을 수 있습니다.", "언제든지 전체 화면 모드와 창 모드로 전환할 수 있습니다.", "선호하는 화이트 노이즈와 날씨를 선택할 수 있습니다.", "다양한 생각을 기록하기 위해 포스트잇을 사용할 수 있습니다.", "온라인 채팅방 기능을 사용하여 전 세계 플레이어와 채팅할 수 있습니다! \n(이 기능은 설정에서 비활성화할 수 있습니다)"]
        text_tutorial = ["튜토리얼", "포모도로 타이머", "할 일 목록", "허브", "전화", "액세서리", "장면", "우편함", "전체 화면 모드", "날씨 & 소리", "포스트잇", "라이브 채팅"]
    }
    if (obj_controller.current_language == 7)
    {
        pages = ["Willkommen bei Chill Pulse, einem Spiel, das darauf ausgelegt ist, Spieler beim Konzentrieren und Entspannen zu unterstützen. Spieler können unterschiedliche Konzentrationsumgebungen freischalten, ihre Lieblingsszenen wählen und ihre Lieblingsmusik spielen, um ihre Konzentrationsreise zu beginnen. Das Gameplay wird anschließend eingeführt.", "Sie können einen Pomodoro-Timer verwenden, um eine Zeit für konzentrierte Arbeit einzustellen. Durch Konzentration verdienen Sie Diamanten und Konzentrationspunkte. Konzentrationspunkte können für Upgrades verwendet werden, während Diamanten für Dekorationen, Haustiere und mehr ausgegeben werden können. Je höher Ihr Level, desto mehr Diamanten verdienen Sie.", "Sie können eine To-Do-Liste verwenden, um alle Ihre Aufgaben zu verfolgen. Alle abgeschlossenen Artikel werden im Kalender gespeichert, den Sie bei Bedarf einsehen und löschen können.", "Sie können auf das Hub zugreifen, wo alle Ihre Konzentrationsaufzeichnungen, Tagebücher und Spieleinstellungen gespeichert sind.", "Dies ist Ihr Kommunikationsgerät, sehen Sie nach, wer Sie vielleicht für einen Chat kontaktieren könnte!", "Hier können Sie Charakteroutfits ändern, Haustiere freischalten und Fische halten.", "Hier können Sie durch die Zeit reisen und charakteristische Szenen aus verschiedenen Zeiten erkunden.", "Hier können Sie Briefe senden und herzliche Worte mit Fremden aus der anderen Seite der Welt austauschen.", "Sie können jederzeit zwischen dem Vollbildmodus und dem Fenstermodus wechseln.", "Sie können Ihr bevorzugtes weißes Rauschen und Wetter wählen.", "Sie können Haftnotizen verwenden, um Ihre verschiedenen Gedanken zu notieren.", "Sie können die Online-Chatraum-Funktion nutzen, um mit Spielern aus der ganzen Welt zu chatten! \n(Diese Funktion kann in den Einstellungen deaktiviert werden)"]
        text_tutorial = ["Tutorial", "Pomodoro-Timer", "To-Do-Liste", "Hub", "Telefon", "Accessoires", "Szene", "Briefkasten", "Vollbildmodus", "Wetter & Geräusche", "Haftnotizen", "Livechat"]
    }
    if (obj_controller.current_language == 8)
    {
        pages = ["Bienvenido a Chill Pulse, un juego diseñado para ayudar a los jugadores a concentrarse y relajarse. Los jugadores pueden desbloquear diferentes ambientes de enfoque, elegir sus escenas favoritas y reproducir su música favorita para comenzar su viaje de concentración. A continuación, se introducirá la jugabilidad.", "Puedes usar un temporizador Pomodoro para establecer un período de trabajo enfocado. Concentrarte te ganará diamantes y puntos de enfoque. Los puntos de enfoque se pueden usar para mejoras, mientras que los diamantes se pueden gastar en decoraciones, mascotas y más. Cuanto mayor sea tu nivel, más diamantes ganarás.", "Puedes usar una lista de tareas para realizar un seguimiento de todas tus tareas. Todos los elementos completados se guardarán en el calendario, que puedes consultar y eliminar según sea necesario.", "Puedes acceder al Hub, donde se almacenan todos tus registros de enfoque, diarios y configuraciones de juego.", "Este es tu dispositivo de comunicación, ¡mira quién podría contactarte para chatear!", "Aquí puedes cambiar los atuendos de los personajes, desbloquear mascotas y mantener peces.", "Aquí puedes viajar en el tiempo y explorar escenas características de diferentes períodos.", "Aquí puedes enviar cartas e intercambiar palabras cálidas con extraños del otro lado del mundo.", "Puedes cambiar entre el modo de pantalla completa y el modo ventana en cualquier momento.", "Puedes elegir tu ruido blanco y clima favoritos.", "Puedes usar notas adhesivas para registrar tus diversos pensamientos.", "¡Puedes usar la función de sala de chat en línea para chatear con jugadores de todo el mundo! (Esta función se puede desactivar en la configuración)"]
        text_tutorial = ["Tutorial", "Temporizador Pomodoro", "Lista de Tareas", "Hub", "Teléfono", "Accesorios", "Escena", "Buzón", "Modo de pantalla completa", "Clima y Sonidos", "Notas Adhesivas", "Chat en vivo"]
    }
    if (obj_controller.current_language == 9)
    {
        pages = ["Benvenuti a Chill Pulse, un gioco progettato per aiutare i giocatori a concentrarsi e rilassarsi. I giocatori possono sbloccare diversi ambienti di concentrazione, scegliere le loro scene preferite e riprodurre la loro musica preferita per iniziare il loro viaggio di concentrazione. Il gameplay verrà introdotto in seguito.", "Puoi usare un timer Pomodoro per impostare un periodo di lavoro concentrato. Concentrarsi ti farà guadagnare diamanti e punti di concentrazione. I punti di concentrazione possono essere utilizzati per miglioramenti, mentre i diamanti possono essere spesi in decorazioni, animali domestici e altro ancora. Più alto è il tuo livello, più diamanti guadagnerai.", "Puoi usare una lista di cose da fare per tenere traccia di tutti i tuoi compiti. Tutti gli elementi completati saranno salvati nel calendario, che puoi visualizzare e cancellare secondo necessità.", "Puoi accedere all'Hub, dove sono conservati tutti i tuoi record di concentrazione, diari e impostazioni di gioco.", "Questo è il tuo dispositivo di comunicazione, guarda chi potrebbe contattarti per una chat!", "Qui puoi cambiare gli outfit dei personaggi, sbloccare animali domestici e tenere pesci.", "Qui puoi viaggiare nel tempo ed esplorare scene caratteristiche di diversi periodi.", "Qui puoi inviare lettere e scambiare parole calorose con estranei dall'altra parte del mondo.", "Puoi passare in qualsiasi momento dalla modalità a schermo intero alla modalità finestra.", "Puoi scegliere il tuo rumore bianco e il meteo preferiti.", "Puoi usare post-it per registrare i tuoi vari pensieri.", "Puoi usare la funzione della chat online per parlare con giocatori di tutto il mondo! (Questa funzione può essere disattivata nelle impostazioni)"]
        text_tutorial = ["Tutorial", "Timer Pomodoro", "Lista delle Cose da Fare", "Hub", "Telefono", "Accessori", "Scena", "Cassetta Postale", "Modalità a schermo intero", "Meteo & Suoni", "Post-it", "Chat dal vivo"]
    }
    if (obj_controller.current_language == 10)
    {
        pages = ["Bem-vindo ao Chill Pulse, um jogo projetado para ajudar os jogadores a focar e relaxar. Os jogadores podem desbloquear diferentes ambientes de foco, escolher suas cenas favoritas e tocar sua música favorita para iniciar sua jornada de concentração. A jogabilidade será introduzida a seguir.", "Você pode usar um temporizador Pomodoro para definir um período de trabalho focado. Se concentrar te ganhará diamantes e pontos de foco. Pontos de foco podem ser usados para melhorias, enquanto diamantes podem ser gastos em decorações, pets e mais. Quanto maior seu nível, mais diamantes você ganha.", "Você pode usar uma lista de tarefas para acompanhar todas as suas tarefas. Todos os itens concluídos serão salvos no calendário, que você pode visualizar e deletar conforme necessário.", "Você pode acessar o Hub, onde todos os seus registros de foco, diários e configurações de jogo são armazenados.", "Este é o seu dispositivo de comunicação, veja quem pode contatar você para um bate-papo!", "Aqui você pode mudar os trajes dos personagens, desbloquear pets e manter peixes.", "Aqui, você pode viajar no tempo e explorar cenas características de diferentes períodos.", "Aqui, você pode enviar cartas e trocar palavras calorosas com estranhos do outro lado do mundo.", "Você pode alternar entre o modo de tela cheia e o modo de janela a qualquer momento.", "Você pode escolher seu ruído branco e clima favoritos.", "Você pode usar notas adesivas para registrar seus diversos pensamentos.", "Você pode usar a função de sala de bate-papo online para conversar com jogadores de todo o mundo! (Esta função pode ser desativada nas configurações)"]
        text_tutorial = ["Tutorial", "Temporizador Pomodoro", "Lista de Tarefas", "Hub", "Telefone", "Acessórios", "Cena", "Caixa de Correio", "Modo de tela cheia", "Clima & Sons", "Notas Adesivas", "Chat ao vivo"]
    }
}

