function drink_info_pr() //gml_Script_drink_info_pr
{
    if (current_scene == 0)
    {
        list_drink_material = ["Leite", "Café", "Xarope"]
        drink_menu = ["Copo Harmonia", "Espresso Intenso", "Leite", "Espresso Veludo", "Café Dulcíssimo", "Briza Doce de Mel", "Conforto Nublado", "Seda de Xarope", "Cascata de Creme", "Essência Doce"]
        drink_descrip = ["Uma mistura perfeitamente equilibrada de café, leite e um toque de doçura, harmonizando todos os sabores.", "Um shot de espresso puro e forte para aqueles que apreciam o sabor inalterado do café.", "Apenas leite quente", "Suave e cremoso, esta bebida combina a profundidade rica do café com a textura aveludada do leite.", "Um café ousado suavizado por um toque de doçura, ideal para uma experiência suavemente estimulante.", "Ligeiramente cafeinado e agradavelmente doce, perfeito para quem gosta de um toque suave de café.", "Uma bebida cremosa de leite com um final doce, ideal para momentos de relaxamento.", "Leite sedoso enriquecido com xarope duplo para um sabor luxuosamente doce.", "Uma cascata de leite cremoso flui sobre uma base de café rico, criando uma textura suave e luxuosa.", "Uma mistura intensa, apenas de xarope, para aqueles que apreciam a essência pura e doce."]
    }
    else if (current_scene == 1)
    {
        list_drink_material = ["Destilado", "Suco", "Licor"]
        drink_menu = ["Desligamento", "Bad Touch", "Névoa Cibernética", "Explosão de Fótons", "Piano Man", "Moonblast", "Noite Cromada", "Zumbido Elétrico", "Fluxo de Dados", "Sincronia Neural"]
        drink_descrip = ["Uma bebida que perturba os sentidos, oferecendo um gosto de rebelião contra os senhores digitais.", "Alma quer um… pffft… um Bad Touch.", "Um coquetel misterioso e enigmático, sua essência prateada evocando a incerteza nebulosa do futuro.", "Um coquetel afiado e refrescante, com uma qualidade luminescente que parece carregar energia.", "Uma bebida estranha. Hm… Bebidas promocionais se encaixam facilmente.", "Algo pequeno, doce e gelado.", "Uma bebida fria e elegante para os notívagos urbanos, refletindo o brilho metálico da cidade sob a lua.", "Uma bebida com um chute potente, energizando o bebedor para uma noite de hacking e exploração.", "Um coquetel suave e fluindo, simbolizando o fluxo contínuo de informações no reino cibernético.", "Um shot puro e não diluído de Licor Neon, para aqueles que procuram se conectar diretamente à grade neon."]
    }
    else if (current_scene == 2)
    {
        list_drink_material = ["Chá Verde", "Jasmim", "Goji"]
        drink_menu = ["Brisa de Jade", "Amanhecer de Jasmim", "Elixir da Imortalidade", "Flor da Trindade", "Dama do Dragão", "Néctar Real", "Vestígio de Beleza", "Segredo Imperial", "Flores ao Luar", "Orquídea do Erudito"]
        drink_descrip = ["Puro prazer do chá verde, refrescante e rejuvenescedor, favorito entre os antigos eruditos e poetas.", "Base de chá verde com um toque de fragrância de jasmim, fresco e elegante com um suave perfume floral.", "Uma mistura nutritiva de bagas de goji e o aroma fresco do chá verde, oferecendo saúde e vitalidade.", "Uma harmonia perfeita de três ingredientes, simbolizando um equilíbrio e união de sabores.", "Dominantemente perfumado de jasmim com uma base de chá verde, persistindo como o toque de uma antiga beleza tocando guqin.", "Jasmim perfumado emparelhado com doces bagas de goji, realçando um ao outro, semelhante a um passeio por um jardim celestial.", "Centrado nos benefícios de saúde das bagas de goji complementadas pela frescura do chá verde, uma bebida para a longevidade.", "Uma mistura nutritiva de goji com o jasmim aromático, outrora uma bebida real de eleição.", "Chá puro de jasmim, intensamente floral e calmante, celebrado por suas qualidades serenas e aroma delicioso.", "Exclusivamente preparado a partir de bagas de goji, simbolizando a nobreza e longevidade de um erudito."]
    }
    else if (current_scene == 3)
    {
        list_drink_material = ["Uísque", "Rum", "Vermute"]
        drink_menu = ["Rob Roy", "Prego Enferrujado", "Manhattan Perfeito", "Velho Cubano", "Dark 'n' Stormy", "Carro de Cabo", "Mai Tai", "Negroni", "Vieux Carré", "Punch do Plantador"]
        drink_descrip = ["Um coquetel clássico à base de uísque escocês, simples mas elegante.", "Uma mistura de uísque e rum, combinando doçura com força.", "Uma variante do coquetel Manhattan, equilibrando vermute com uísque.", "Misturando sabores clássicos cubanos com uísque e vermute.", "O poder do rum, profundo e cativante.", "Inspirado pelos bondinhos de São Francisco, combinando rum e uísque.", "Um clássico sabor tropical, maravilhosamente misturando rum e vermute.", "Um coquetel italiano clássico dominado por vermute, agridoce.", "Um coquetel clássico de Nova Orleans, complexo e profundo.", "Um coquetel caribenho tradicional, conhecido por seus sabores ousados e sabor robusto."]
    }
    else if (current_scene == 4)
    {
        list_drink_material = ["Ervas", "Frutas Vermelhas", "Vinho"]
        drink_menu = ["Infusão do Herbalista", "Néctar de Bagas Silvestres", "Reserva do Monge", "Rascunho de Bagas do Vinicultor", "Mistura do Barão", "Jubileu de Bagas", "Veludo Vintage", "Mistura do Jardineiro", "Elixir do Boticário", "Colheita Farta"]
        drink_descrip = ["Elaborado a partir de um trio de ervas finas, este tônico é reverenciado por suas qualidades medicinais e revigorantes.", "Uma mistura exuberante e refrescante de frutas vermelhas maduras com um toque de essência de ervas, evocando a frescura da floresta.", "Uma receita sagrada que combina a santidade das ervas com a riqueza do vinho envelhecido em mosteiros.", "Uma vibrante combinação onde a suculência das frutas se encontra com a sofisticação do vinho fino.", "Uma mistura nobre com a audácia do vinho e um toque de fruta, digna da aristocracia.", "Uma celebração das frutas em sua forma mais pura, esta bebida é um festival de doçura natural.", "Uma mistura requintada de safras selecionadas, criada para oferecer um sabor rico e luxuoso.", "Uma mistura terrosa e deliciosa que captura a essência de um jardim bem cuidado e de um bom vinho.", "Uma potente mistura estimada por suas propriedades digestivas e calmantes, inspirada em receitas tradicionais de boticário.", "Abrigando a abundância da colheita, esta mistura mostra o sabor completo das frutas maduras com um toque final de vinho."]
    }
    else if (current_scene == 5)
    {
        list_drink_material = ["Água Eletrolítica", "Concentrado de Proteína", "Gelatina de Vitaminas"]
        drink_menu = ["Brilho Eletrolítico", "Pulso de Proteína", "Oscilação Microgravitacional", "Cromáticos de Vitaminas", "Cristais de Energia", "Gelatina Multiespectro", "Escudo Antirradiação", "Gelatina Sensorial", "Fluido de Biofeedback", "Sobremesa Espacial"]
        drink_descrip = ["Esta bebida utiliza uma fórmula especial de equilíbrio eletrolítico que brilha sob luz, melhorando a segurança durante atividades noturnas.", "Utiliza nanotecnologia para permitir uma rápida absorção de proteína no corpo, ideal para rápida reposição de energia após tarefas espaciais de alta intensidade.", "Infundida com micro-nanobolhas que criam efeitos de oscilação interessantes em um ambiente de microgravidade, oferecendo uma experiência de bebida única.", "Esta bebida contém gelatina de vitaminas que muda de cor de acordo com os níveis de pH, permitindo que os astronautas monitorem visualmente sua ingestão de vitaminas.", "Caracteriza formas cristalinas de proteína que se dissolvem lentamente, liberando energia e nutrientes continuamente, adequadas para tarefas de longa duração.", "Cada cor da gelatina representa um espectro nutricional diferente, permitindo que os astronautas escolham com base em suas necessidades nutricionais.", "Incorpora componentes especiais antirradiação para ajudar a reduzir os danos por radiação no espaço, enquanto também fornece um aumento de força.", "Esta bebida ajusta automaticamente sua doçura e textura de acordo com o estado corporal do astronauta, reabastecendo energia e nutrientes de maneira ótima.", "Contém sensores de biofeedback que podem monitorar e ajustar o conteúdo nutricional em tempo real para atender às necessidades específicas dos astronautas.", "Projetada para parecer e ter gosto de uma sobremesa terrestre, proporcionando conforto e familiaridade enquanto é rica em nutrientes."]
    }
}

