function drink_info_es() //gml_Script_drink_info_es
{
    if (current_scene == 0)
    {
        list_drink_material = ["Leche", "Café", "Jarabe"]
        drink_menu = ["Copa de Armonía", "Espresso Intenso", "Leche", "Espresso de Terciopelo", "Café Dulce", "Brisa de Miel", "Confort Nuboso", "Seda de Jarabe", "Cascada de Crema", "Esencia Dulce"]
        drink_descrip = ["Una mezcla perfectamente equilibrada de café, leche y un toque de dulzura, armonizando todos los sabores.", "Un puro y fuerte shot de espresso para aquellos que aprecian el sabor inalterado del café.", "Simplemente leche caliente.", "Suave y cremoso, esta bebida combina la rica profundidad del café con la textura aterciopelada de la leche.", "Un café audaz suavizado con un toque de dulzura, ideal para una experiencia ligeramente estimulante.", "Ligeramente cafeinado y dulcemente aromatizado, perfecto para aquellos que disfrutan de un toque suave de café.", "Una reconfortante y cremosa bebida láctea con un dulce final, ideal para momentos de relajación.", "Leche sedosa enriquecida con doble jarabe para un sabor lujosamente dulce.", "Una cascada de leche cremosa fluye sobre una base de café rico, creando una textura suave y exuberante.", "Una intensa mezcla, solo de jarabe, para aquellos que saborean la pura esencia dulce."]
    }
    else if (current_scene == 1)
    {
        list_drink_material = ["Espíritu", "Jugo", "Licor"]
        drink_menu = ["Cortocircuito", "Bad Touch", "Niebla Cibernética", "Explosión de Fotones", "Piano Man", "Moonblast", "Noche Cromada", "Zumbido Eléctrico", "Corriente de Datos", "Sincronización Neural"]
        drink_descrip = ["Una bebida que perturba los sentidos, ofreciendo un sabor de rebelión contra los señores digitales.", "Alma quiere un… pffft… un Bad Touch.", "Un misterioso y enigmático cóctel, cuya esencia plateada evoca la nebulosa incertidumbre del futuro.", "Un cóctel agudo y refrescante, con una calidad luminiscente que parece estar cargada de energía.", "Una bebida rara. Hm… Las bebidas de promoción encajan fácilmente.", "Algo pequeño, dulce y helado.", "Una bebida fresca y elegante para los noctámbulos urbanos, reflejando el brillo metálico de la ciudad bajo la luna.", "Una bebida con un potente impulso, energizando al bebedor para una noche de hacking y exploración.", "Un cóctel suave y fluido, simbolizando el flujo interminable de información en el reino cibernético.", "Un trago puro y sin diluir de Licor Neón, para aquellos que buscan conectarse directamente a la red de neón."]
    }
    else if (current_scene == 2)
    {
        list_drink_material = ["Té Verde", "Jazmín", "Goji"]
        drink_menu = ["Brisa de Jade", "Amanecer de Jazmín", "Elixir de Inmortalidad", "Flor de la Trinidad", "Dama del Dragón", "Néctar Real", "Remanente de Belleza", "Secreto Imperial", "Flores a la Luz de la Luna", "Orquídea del Sabio"]
        drink_descrip = ["Placer puro del té verde, refrescante y rejuvenecedor, favorito entre los antiguos eruditos y poetas.", "Base de té verde con un toque de fragancia de jazmín, fresco y elegante con un suave perfume floral.", "Una mezcla nutritiva de bayas de goji y el aroma fresco del té verde, ofreciendo salud y vitalidad.", "Una armonía perfecta de tres ingredientes, simbolizando un equilibrio y unidad de sabores.", "Dominantemente perfumado de jazmín con una base de té verde, persistiendo como el toque de una antigua belleza tocando el guqin.", "Jazmín perfumado emparejado con dulces bayas de goji, realzándose mutuamente, similar a un paseo por un jardín celestial.", "Centrado en los beneficios para la salud de las bayas de goji complementadas por la frescura del té verde, una bebida para la longevidad.", "Una mezcla nutritiva de goji con el jazmín aromático, antes una bebida real de elección.", "Té puro de jazmín, intensamente floral y calmante, celebrado por sus cualidades serenas y aroma delicioso.", "Exclusivamente elaborado a partir de bayas de goji, simbolizando la nobleza y longevidad de un erudito."]
    }
    else if (current_scene == 3)
    {
        list_drink_material = ["Whisky", "Ron", "Vermut"]
        drink_menu = ["Rob Roy", "Clavo Oxidado", "Manhattan Perfecto", "Viejo Cubano", "Tormenta Oscura", "Carro de Cable", "Mai Tai", "Negroni", "Vieux Carré", "Puñetazo del Plantador"]
        drink_descrip = ["Un cóctel clásico a base de whisky escocés, simple pero elegante.", "Una mezcla de whisky y ron, combinando dulzura con fuerza.", "Una variante del cóctel Manhattan, equilibrando vermut con whisky.", "Mezclando sabores clásicos cubanos con whisky y vermut.", "El poder del ron, profundo y cautivador.", "Inspirado en los tranvías de San Francisco, combinando ron y whisky.", "Un sabor tropical clásico, maravillosamente mezclando ron y vermut.", "Un cóctel italiano clásico dominado por el vermut, agridulce.", "Un cóctel clásico de Nueva Orleans, complejo y profundo.", "Un cóctel caribeño tradicional, conocido por sus sabores audaces y su sabor robusto."]
    }
    else if (current_scene == 4)
    {
        list_drink_material = ["Hierbas", "Bayas", "Vino"]
        drink_menu = ["Breve del Herbolario", "Néctar de Madera de Bayas", "Reserva del Monje", "Borrador de Bayas del Vinicultor", "Mezcla del Barón", "Jubileo de Bayas", "Terciopelo Vintage", "Mezcla del Jardinero", "Elixir del Boticario", "Cosecha Fructífera"]
        drink_descrip = ["Elaborado a partir de un trío de finas hierbas, este tónico es venerado por sus cualidades medicinales y revitalizantes.", "Una mezcla exuberante y refrescante de bayas maduras con un toque de esencia herbal, que evoca la frescura del bosque.", "Una receta sagrada que combina la santidad de las hierbas con la riqueza del vino añejado en monasterios.", "Una vibrante mezcla donde la jugosidad de las bayas se encuentra con la sofisticación del vino fino.", "Una noble mezcla con la audacia del vino y un toque de bayas, digna de la aristocracia.", "Una celebración de bayas en su forma más pura, esta bebida es un festival de dulzura natural.", "Una exquisita mezcla de añadas seleccionadas, elaborada para ofrecer un sabor rico y lujoso.", "Una mezcla terrenal y deliciosa que captura la esencia de un jardín bien cuidado y un buen vino.", "Una poderosa mezcla apreciada por sus propiedades digestivas y calmantes, inspirada en recetas tradicionales de boticario.", "Abrazando la abundancia de la cosecha, esta mezcla muestra el sabor completo de las bayas maduras con un final de vino."]
    }
    else if (current_scene == 5)
    {
        list_drink_material = ["Agua Electrolítica", "Concentrado de Proteína", "Gelatina de Vitaminas"]
        drink_menu = ["Brillo Electrolítico", "Pulso de Proteína", "Oscilación Microgravedad", "Cromáticos de Vitaminas", "Cristales de Energía", "Gelatina Multiespectro", "Escudo Radiactivo", "Gelatina Sensorial", "Fluido de Biofeedback", "Postre Espacial"]
        drink_descrip = ["Esta bebida utiliza una fórmula especial de balance electrolítico que brilla bajo la luz, mejorando la seguridad durante actividades nocturnas.", "Utiliza nanotecnología para permitir una rápida absorción de proteínas en el cuerpo, ideal para la recarga rápida de energía después de tareas espaciales de alta intensidad.", "Infundida con micro-nanoburbujas que crean efectos de oscilación interesantes en un entorno de microgravedad, ofreciendo una experiencia de bebida única.", "Esta bebida contiene gelatina de vitaminas que cambia de color según los niveles de pH, permitiendo a los astronautas monitorear visualmente su ingesta de vitaminas.", "Características de formas cristalinas de proteínas que se disuelven lentamente, liberando energía y nutrientes continuamente, adecuadas para tareas de larga duración.", "Cada color de la gelatina representa un espectro nutricional diferente, permitiendo a los astronautas elegir basado en sus necesidades nutricionales.", "Incorpora componentes especiales contra la radiación para ayudar a reducir el daño por radiación en el espacio, mientras también proporciona un impulso en la fuerza.", "Esta bebida ajusta automáticamente su dulzura y textura según el estado corporal del astronauta, reponiendo energía y nutrientes de manera óptima.", "Contiene sensores de biofeedback que pueden monitorear y ajustar el contenido nutricional en tiempo real para satisfacer las necesidades específicas de los astronautas.", "Diseñada para parecerse y saber como un postre terrestre, proporcionando confort y familiaridad mientras es rica en nutrientes."]
    }
}

